// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationFormat } from './AnimationFormat';

export type AnimationProps = { src?: string; area?: [number, number, number, number]; format?: AnimationFormat };
