// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings for audio playback, including delay, start position, volume, etc.
 */
export type AudioSettings = {
  /**
   * Optional delay time in seconds before the audio starts playing.
   */
  delayTime?: number;
  /**
   * The position in seconds where the audio should start playing.
   */
  startPosition?: number;
  /**
   * Whether the sound should be played in reverse.
   */
  reverse?: boolean;
  /**
   * Loop region defined by a start and end time in seconds. `-1` for end means loop to the end of the audio.
   */
  loopRegion?: [number, number];
  /**
   * Volume of the audio, ranges from 0.0 (silence) to 1.0 (normal volume),
   * values greater than 1.0 can be used for amplification.
   */
  volume?: number;
  /**
   * Playback rate of the audio, where 1.0 is normal speed.
   */
  playbackRate?: number;
  /**
   * Panning value from -1.0 (left) to 1.0 (right), with 0.0 being center.
   */
  panning?: number;
  /**
   * Whether the audio should start playing automatically after loading.
   */
  autoPlay?: boolean;
  /**
   * Optional fade time in milliseconds for audio transitions.
   */
  fadeTime?: number;
};
