// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioSettings } from './AudioSettings';

export type AudioCommand =
  | { subCommand: 'load'; name: string; src: string; settings?: AudioSettings }
  | { subCommand: 'release'; name: string; fadeTime?: number; silentFail?: boolean }
  | { subCommand: 'play'; name: string; fadeTime?: number; waitForEnd?: boolean }
  | { subCommand: 'stop'; name: string; fadeTime?: number }
  | { subCommand: 'pause'; name: string; fadeTime?: number }
  | { subCommand: 'resume'; name: string; fadeTime?: number }
  | { subCommand: 'setVolume'; name: string; volume: number; fadeTime?: number }
  | { subCommand: 'setGlobalVolume'; name: string; volume: number }
  | { subCommand: 'seekBy'; name: string; time: number }
  | { subCommand: 'seekTo'; name: string; time: number }
  | { subCommand: 'setPlaybackRate'; name: string; rate: number }
  | { subCommand: 'setLoopRegion'; name: string; start: number; end: number }
  | { subCommand: 'setPanning'; name: string; panning: number };
