// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Custom event for user-defined events
 */
export type CustomEvent<T> = {
  kind: 'CustomEvent';
  /**
   * target node id, or 0 for global
   */
  targetId: number;
  /**
   * event name for `addEventListener` or `onXXX`
   */
  name: string;
  /**
   * event body, pass as parameter to callback
   */
  body?: T;
};
