// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditableCommand =
  | { subCommand: 'getState' }
  | { subCommand: 'setValue'; value: string }
  | { subCommand: 'setCaretRect'; x: number; y: number; width: number; height: number };
