// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditableChangeSource } from './EditableChangeSource';
import type { EditableState } from './EditableState';

export type EditableEvent =
  | { type: 'focus'; state: EditableState }
  | { type: 'blur'; state: EditableState }
  | { type: 'input'; state: EditableState }
  | { type: 'change'; state: EditableState; source: EditableChangeSource }
  | { type: 'compositionStart'; state: EditableState }
  | { type: 'compositionUpdate'; state: EditableState }
  | { type: 'compositionEnd'; state: EditableState };
