// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutableRestartBoundary =
  | { kind: 'checkpoint'; checkpointKey: string }
  | { kind: 'restart-story'; story: string; entry: string }
  | { kind: 'restart-paragraph'; story: string; paragraph: string };
