// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 滤镜配置（可序列化，用于 JS 互操作）
 */
export type FilterKind =
  | { type: 'blur-perfect'; radius: number }
  | { type: 'blur'; radius: number; continuous?: boolean }
  | { type: 'brightness'; amount: number }
  | { type: 'contrast'; amount: number }
  | { type: 'saturation'; amount: number }
  | { type: 'hue-rotate'; degrees: number }
  | { type: 'grayscale'; amount: number }
  | { type: 'sepia'; amount: number }
  | { type: 'invert'; amount: number }
  | { type: 'unknown' };
