// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The GamepadHapticActuator interface of the [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API)
 * represents hardware in the controller designed to provide haptic feedback to the user (if available),
 * most commonly vibration hardware.
 */
export type GamepadHapticActuator = {
  /**
   * Returns an array of enumerated values representing the different haptic effects that the actuator supports.
   */
  effects: Array<string>;
};
