// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gamepad } from './Gamepad';
import type { GamepadButton } from './GamepadButton';

export type GamepadEvent =
  | { gamepad: Gamepad }
  | { gamepad: Gamepad; button: GamepadButton }
  | { gamepad: Gamepad; axis: number; value: number };
