// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The GamepadButton interface defines an individual button of a gamepad or other controller, allowing
 * access to the current state of different types of buttons available on the control device.
 */
export type GamepadButton = {
  /**
   * A boolean value indicating whether the button is currently pressed (`true`) or unpressed (`false`).
   */
  pressed: boolean;
  /**
   * A boolean value indicating whether the button is currently touched (`true`) or not touched (`false`).
   */
  touched: boolean;
  /**
   * A double value used to represent the current state of analog buttons, such as the triggers on many
   * modern gamepads. The values are normalized to the range 0.0 — 1.0, with 0.0 representing a button that
   * is not pressed, and 1.0 representing a button that is fully pressed.
   */
  value: number;
};
