// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectParams } from './EffectParams';

export type GamepadCommand =
  | { subCommand: 'getGamepads' }
  | { subCommand: 'playEffect'; index: number; effect: string; params: EffectParams };
