// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GamepadButton } from './GamepadButton';
import type { GamepadHapticActuator } from './GamepadHapticActuator';

/**
 * The Gamepad interface of the [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API)
 * defines an individual gamepad or other controller, allowing access to information such as button presses,
 * axis positions, and id.
 */
export type Gamepad = {
  /**
   * A string containing identifying information about the controller.
   */
  id: string;
  /**
   * An integer that is auto-incremented to be unique for each device currently connected to the system.
   */
  index: number;
  /**
   * A boolean indicating whether the gamepad is still connected to the system.
   */
  connected: boolean;
  /**
   * A string indicating whether the browser has remapped the controls on the device to a known layout.
   * Currently, the only value that is returned is "standard", which indicates that the browser has
   * remapped the controls to a standard layout.
   * See [gamepad#remapping](https://w3c.github.io/gamepad/#remapping)
   */
  mapping: string;
  /**
   * An array of [GamepadButton] objects representing the buttons present on the device.
   */
  buttons: Array<GamepadButton>;
  /**
   * An array representing the controls with axes present on the device (e.g. analog thumb sticks).
   */
  axes: Array<number>;
  /**
   * A GamepadHapticActuator object, which represents haptic feedback hardware available on the controller.
   */
  vibrationActuator: GamepadHapticActuator | null;
  /**
   * A f64 representing the last time the data for this gamepad was updated.
   */
  timestamp: number;
};
