// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlignItems } from './AlignItems';
import type { JustifyContent } from './JustifyContent';

export type HBoxProps = {
  width?: number;
  height?: number;
  gap?: number;
  padding?: number;
  paddingX?: number;
  paddingY?: number;
  justifyContent?: JustifyContent;
  alignItems?: AlignItems;
};
