// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Literal = null | string | bigint | number | boolean | Array<Literal> | { [key in string]: Literal };
