// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MouseEventKind =
  | 'MouseEnter'
  | 'MouseLeave'
  | 'MouseDown'
  | 'MouseUp'
  | 'MouseMove'
  | 'Click'
  | 'DoubleClick'
  | 'ContextMenu';
