// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoyuCursor } from './MoyuCursor';

export type NodeProps = {
  label?: string;
  anchor?: [number, number];
  pivot?: [number, number];
  x?: number;
  y?: number;
  scale?: number;
  scaleX?: number;
  scaleY?: number;
  rotation?: number;
  skew?: number;
  skewX?: number;
  skewY?: number;
  visible?: boolean;
  tint?: string;
  opacity?: number;
  interactive?: boolean;
  cursor?: MoyuCursor;
};
