// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlatformInfo = {
  isLinux: boolean;
  isMacOS: boolean;
  isAndroid: boolean;
  isIOS: boolean;
  isWasm: boolean;
  isNative: boolean;
  isDesktop: boolean;
  isMobile: boolean;
  isWeb: boolean;
};
