// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyboardEventKind } from './KeyboardEventKind';
import type { KeyboardLocation } from './KeyboardLocation';

export type RawKeyboardEvent = {
  kind: KeyboardEventKind;
  targetId: number;
  bubbleTargetIds: Array<number>;
  key: string;
  code: string;
  location: KeyboardLocation;
  repeat: boolean;
  ctrlKey: boolean;
  shiftKey: boolean;
  altKey: boolean;
  metaKey: boolean;
  isComposing: boolean;
};
