// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MouseEventKind } from './MouseEventKind';

export type RawMouseEvent = {
  kind: MouseEventKind;
  targetId: number;
  bubbleTargetIds: Array<number>;
  clientX: number;
  clientY: number;
  screenX: number;
  screenY: number;
  offsetX: number;
  offsetY: number;
};
