// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MouseEventKind } from './MouseEventKind';

/**
 * A mouse event, carrying the button it is about and the buttons held at the time,
 * both in the DOM `MouseEvent` encoding.
 */
export type RawMouseEvent = {
  kind: MouseEventKind;
  targetId: number;
  bubbleTargetIds: Array<number>;
  /**
   * The button this event is about: 0 left, 1 middle, 2 right, 3 back, 4 forward.
   * Events that are not about a particular button carry 0.
   */
  button: number;
  /**
   * Buttons held when the event fired: 1 left, 2 right, 4 middle, 8 back, 16 forward.
   */
  buttons: number;
  ctrlKey: boolean;
  shiftKey: boolean;
  altKey: boolean;
  metaKey: boolean;
  /**
   * True when the engine produced this event rather than a mouse device: the mouse
   * compatibility gesture of a touch tap, and the hover refresh a frame performs while
   * the pointer stays where it is. A consumer that wants to know whether the user is
   * operating a mouse should ignore synthetic events.
   */
  synthetic: boolean;
  clientX: number;
  clientY: number;
  screenX: number;
  screenY: number;
  offsetX: number;
  offsetY: number;
};
