// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TouchEventKind } from './TouchEventKind';

export type RawTouchEvent = {
  kind: TouchEventKind;
  targetId: number;
  bubbleTargetIds: Array<number>;
  identifier: number;
  clientX: number;
  clientY: number;
  screenX: number;
  screenY: number;
  offsetX: number;
  offsetY: number;
};
