// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WheelEventDeltaMode } from './WheelEventDeltaMode';

export type RawWheelEvent = {
  targetId: number;
  bubbleTargetIds: Array<number>;
  deltaX: number;
  deltaY: number;
  deltaZ: number;
  deltaMode: WheelEventDeltaMode;
};
