// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Literal } from './Literal';

export type ResolvedArgument = { name: string; value: Literal };
