// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedArgument } from './ResolvedArgument';

export type ResolvedCommandLine = { command: string; arguments: Array<ResolvedArgument> };
