// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedCommandLine } from './ResolvedCommandLine';
import type { ResolvedSystemCallLine } from './ResolvedSystemCallLine';

export type ScenarioEvent =
  | ResolvedCommandLine
  | ResolvedSystemCallLine
  | { leading: string | null; text: string | null; tailing: string | null }
  | null;
