// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from './serde_json/JsonValue';

export type ScenarioCommand =
  | { subCommand: 'addStory'; name: string }
  | { subCommand: 'removeStory'; name: string }
  | { subCommand: 'hasStory'; name: string }
  | { subCommand: 'getStoryList' }
  | {
      subCommand: 'startStory';
      /**
       * The name of the story to start
       */
      name: string;
      /**
       * The entry point to start from
       */
      entry?: string;
    }
  | { subCommand: 'terminateStory' }
  | { subCommand: 'nextLine' }
  | {
      subCommand: 'setWaiting';
      /**
       * waiting time in milliseconds
       * use f64 to avoid conversion issues with JavaScript numbers
       */
      time: number;
      /**
       * whether the waiting can be skipped by user input
       */
      skippable: boolean;
    }
  | { subCommand: 'setVariable'; name: string; value: JsonValue }
  | { subCommand: 'getVariable'; name: string }
  | { subCommand: 'setVariables'; variables: { [key in string]: JsonValue } }
  | { subCommand: 'getVariables' }
  | { subCommand: 'setPermanentVariable'; key: string; value: JsonValue }
  | { subCommand: 'getPermanentVariable'; key: string }
  | { subCommand: 'setPermanentVariables'; variables: { [key in string]: JsonValue } }
  | { subCommand: 'getPermanentVariables' }
  | { subCommand: 'clearPermanentVariables' }
  | { subCommand: 'saveGame'; name: string; extra?: JsonValue }
  | { subCommand: 'record'; meta: { [key in string]: JsonValue } }
  | { subCommand: 'restoreCheckpoint'; key: string }
  | { subCommand: 'clearCheckpoints' }
  | { subCommand: 'getExecutionCursor' }
  | { subCommand: 'getRecords'; offset?: number; limit?: number }
  | { subCommand: 'jumpToRecord'; recordId: string }
  | {
      subCommand: 'loadGame';
      name: string;
      /**
       * if true, will overwrite the current game session with the loaded one,
       * otherwise an error will be returned if the current session is not empty
       */
      overwrite: boolean;
    }
  | { subCommand: 'resetGame' }
  | { subCommand: 'removeGame'; name: string }
  | {
      subCommand: 'getGameList';
      /**
       * matches the name of the game session
       */
      pattern?: string;
    };
