// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedCommandLine } from './ResolvedCommandLine';
import type { ResolvedSystemCallLine } from './ResolvedSystemCallLine';
import type { TextLine } from './TextLine';

export type ScenarioEvent = ResolvedCommandLine | ResolvedSystemCallLine | TextLine | null;
