// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderSource } from './ShaderSource';
import type { ShaderTimeControl } from './ShaderTimeControl';

export type ShaderProps = {
  width?: number;
  height?: number;
  shader?: ShaderSource;
  timeControl?: ShaderTimeControl;
  displayChannel?: number | null;
};
