// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderDirection } from './ShaderDirection';
import type { ShaderParam } from './ShaderParam';

export type ShaderSource =
  | ({ type: 'builtin' } & (
      | { name: 'crossfade' }
      | { name: 'wipe'; softness: number; direction: ShaderDirection }
      | { name: 'fade'; out: number; hold: number; in: number; color: string }
      | { name: 'push'; direction: ShaderDirection }
      | { name: 'slideaway'; direction: ShaderDirection }
      | { name: 'zoom'; startScale: number; endScale: number; origin: [number, number] }
      | { name: 'pixellate'; steps: number }
      | { name: 'mask'; rule: string; softness: number; reverse: boolean }
    ))
  | { type: 'raw'; content: string; params?: Array<ShaderParam> };
