// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderParamType } from './ShaderParamType';

export type ShaderParam = { name: string; type: ShaderParamType; value: number };
