// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderSlotSpace } from './ShaderSlotSpace';

export type ShaderSlotProps = {
  channel?: number;
  empty?: boolean;
  static?: boolean;
  space?: ShaderSlotSpace;
  width?: number;
  height?: number;
};
