// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderParam } from './ShaderParam';

export type ShaderSource =
  | ({ type: 'builtin' } & (
      | { name: 'crossfade' }
      | { name: 'wipe' }
      | { name: 'fade'; out: number; hold: number; in: number; color: string }
    ))
  | { type: 'raw'; content: string; params?: Array<ShaderParam> };
