// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetainMode } from './RetainMode';

export type ShaderCommand =
  | { subCommand: 'prepare'; fromChannel: number; toChannel: number; mode?: RetainMode }
  | { subCommand: 'perform'; duration: number }
  | { subCommand: 'start' }
  | { subCommand: 'stop' }
  | { subCommand: 'reset' };
