// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderBuiltinName } from './ShaderBuiltinName';

export type ShaderSource = { type: 'builtin'; name: ShaderBuiltinName } | { type: 'raw'; content: string };
