// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShaderParam } from './ShaderParam';
import type { ShaderSource } from './ShaderSource';
import type { ShaderTimeControl } from './ShaderTimeControl';

export type ShaderProps = {
  shader?: ShaderSource;
  params?: Array<ShaderParam>;
  timeControl?: ShaderTimeControl;
  displayChannel?: number | null;
};
