// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShaderSlotProps = { channel?: number; empty?: boolean; static?: boolean; width?: number; height?: number };
