// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NineSliceMode } from './NineSliceMode';
import type { SpriteMode } from './SpriteMode';

export type SpriteProps = {
  src?: string;
  mode?: SpriteMode;
  area?: [number, number, number, number];
  bounds?: [number, number, number, number];
  nineSliceMode?: NineSliceMode;
  targetWidth?: number;
  targetHeight?: number;
};
