// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayDialog } from './OverlayDialog';
import type { OverlayNotificationPosition } from './OverlayNotificationPosition';
import type { OverlayStoreFlag } from './OverlayStoreFlag';
import type { TimelinePossibleClip } from './TimelinePossibleClip';

export type SteamCommand =
  | { subCommand: 'achievementSet'; name: string }
  | { subCommand: 'achievementClear'; name: string }
  | { subCommand: 'achievementClearAll' }
  | { subCommand: 'achievementGet'; name: string }
  | { subCommand: 'achievementIndicateProgress'; name: string; current: number; max: number }
  | { subCommand: 'appsDlcInstalled'; appId: number }
  | { subCommand: 'appsDlcProgress'; appId: number }
  | { subCommand: 'appsGetAppBuildId' }
  | { subCommand: 'appsGetCurrentBetaName' }
  | { subCommand: 'appsGetCurrentGameLanguage' }
  | { subCommand: 'appsGetSteamUiLanguage' }
  | { subCommand: 'appsInstallDlc'; appId: number }
  | { subCommand: 'appsIsSubscribedApp'; appId: number }
  | { subCommand: 'appsUninstallDlc'; appId: number }
  | { subCommand: 'overlayActivate'; dialog: OverlayDialog }
  | { subCommand: 'overlayActivateToStore'; appId: number; flag?: OverlayStoreFlag }
  | { subCommand: 'overlayActivateToWebPage'; url: string }
  | { subCommand: 'overlayIsEnabled' }
  | { subCommand: 'overlayNeedsPresent' }
  | { subCommand: 'overlaySetNotificationPosition'; position: OverlayNotificationPosition }
  | { subCommand: 'statsClearAchievement'; name: string }
  | { subCommand: 'statsGetAchievement'; name: string }
  | { subCommand: 'statsGetFloatStat'; name: string }
  | { subCommand: 'statsGetIntStat'; name: string }
  | { subCommand: 'statsSetAchievement'; name: string }
  | { subCommand: 'statsIndicateAchievementProgress'; name: string; current: number; max: number }
  | { subCommand: 'statsListAchievements' }
  | { subCommand: 'statsSetFloatStat'; name: string; value: number }
  | { subCommand: 'statsSetIntStat'; name: string; value: number }
  | { subCommand: 'statsStoreStats' }
  | {
      subCommand: 'timelineAddEvent';
      icon: string;
      title: string;
      description: string;
      priority?: number;
      startOffsetSeconds?: number;
      durationSeconds?: number;
      possibleClip?: TimelinePossibleClip;
    }
  | { subCommand: 'timelineClearStateDescription'; timeDeltaSeconds?: number }
  | { subCommand: 'timelineSetStateDescription'; description: string; timeDeltaSeconds?: number }
  | { subCommand: 'userGetAccountId' }
  | { subCommand: 'userGetCSteamId' }
  | { subCommand: 'userGetGameBadgeLevel'; series: number; foil: boolean }
  | { subCommand: 'userGetPersonaName' }
  | { subCommand: 'workshopGetSubscribedItemPath'; itemId: string }
  | { subCommand: 'workshopGetSubscribedItems'; includeDisabled?: boolean };
