// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutableRestartBoundary } from './ExecutableRestartBoundary';
import type { StoryReplaceMode } from './StoryReplaceMode';

export type StoryReplaceExecutionPlan = {
  mode: StoryReplaceMode;
  boundary?: ExecutableRestartBoundary;
  targetMarkerId?: string;
  changedControlFlow: boolean;
};
