// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReadFormat } from './ReadFormat';
import type { WindowState } from './WindowState';

export type SystemCommand =
  | { subCommand: 'setWindowSize'; width: number; height: number; factor?: number }
  | { subCommand: 'setWindowState'; state: WindowState }
  | { subCommand: 'setTitle'; title: string }
  | { subCommand: 'getWindowState' }
  | { subCommand: 'getWindowInnerPosition' }
  | { subCommand: 'getWindowInnerSize' }
  | { subCommand: 'getStageSize' }
  | { subCommand: 'takeSnapshot'; width?: number; height?: number; keepAspectRatio?: boolean }
  | { subCommand: 'readFile'; path: string; format?: ReadFormat }
  | { subCommand: 'getParams' }
  | { subCommand: 'quit' };
