// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextPrintMode } from './TextPrintMode';

/**
 * To be compatible with react-spring inside JS runtime, we have to flatten the struct.
 * FIXME: But `#[serde(flatten)]` works not quite well when there are more than one `#[serde(flatten)]` in a struct.
 * So we do it manually.
 */
export type TextProps = {
  text?: string;
  printMode?: TextPrintMode;
  printSpeed?: number;
  parseMarkup?: boolean;
  /**
   * the writing direction of the text in the box,
   * only `Horizontal` (right-to-left) or `Vertical` (top-to-bottom) is valid.
   */
  direction?: 'horizontal' | 'vertical';
  /**
   * the width of box.
   */
  boxWidth?: number;
  /**
   * the height of box.
   */
  boxHeight?: number;
  /**
   * the size of the glyph grid which each character be fit to, usually equals to `font_size`.
   */
  glyphGridSize?: number;
  fontSize?: number;
  fillColor?: string;
  lineHeight?: number;
  indent?: number;
  stroke?: boolean;
  shadow?: boolean;
  strokeColor?: string;
  strokeWidth?: number;
  shadowColor?: string;
  shadowOffsetX?: number;
  shadowOffsetY?: number;
  shadowBlur?: number;
  shadowWidth?: number;
};
