// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Text print mode
 */
export type TextPrintMode = 'instant' | 'typewriter' | 'printer';
