// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PointerEventKind } from './PointerEventKind';

export type TextInteractionEvent = { id: string; kind: PointerEventKind };
