// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TextLine = { leading: string | null; text: string | null; tailing: string | null };
