// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TextCommand =
  | { subCommand: 'setText'; text: string; instant?: boolean }
  | { subCommand: 'finishPrinting' }
  | { subCommand: 'getCursorPosition' };
