// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetainMode } from './RetainMode';
import type { TransitionEffect } from './TransitionEffect';

export type TransitionContainerCommand =
  | { subCommand: 'prepare'; retain?: RetainMode }
  | { subCommand: 'perform'; effect: TransitionEffect; duration: number };
