// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransitionSlotPhase } from './TransitionSlotPhase';

export type TransitionSlotProps = { phase?: TransitionSlotPhase };
