// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoProps = { src: string | null; loop?: boolean; autoPlay?: boolean; volume?: number; muted?: boolean };
