// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoCommand =
  | { subCommand: 'play' }
  | { subCommand: 'pause' }
  | { subCommand: 'resume' }
  | { subCommand: 'stop' }
  | { subCommand: 'seek'; time: number }
  | { subCommand: 'setVolume'; volume: number }
  | { subCommand: 'setMuted'; muted: boolean }
  | { subCommand: 'setLoop'; enabled: boolean };
