name: Rust

on:
  push:
    branches:
      - master
      - feat/*
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.wasm && '(Webassembly)' || '' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            wasm: false
          - os: ubuntu-latest
            wasm: true
          - os: macOS-latest
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest' && matrix.wasm == false
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev

      - name: Build Binary
        run: cargo build --verbose
        if: matrix.wasm == false

      - name: Build Web
        run: |
          rustup target add wasm32-unknown-unknown
          cargo build -p doufu --lib --target wasm32-unknown-unknown
        if: matrix.wasm == true
